name: Split transcript into calls

on:
  repository_dispatch:
    types: [split]

permissions:
  contents: write

jobs:
  split:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r scripts/requirements.txt
      - name: Detect and split calls
        env:
          VIDEO_ID: ${{ github.event.client_payload.videoId }}
          LANGUAGE: ${{ github.event.client_payload.language || 'en' }}
          MAX_DURATION: ${{ github.event.client_payload.maxDuration || 420 }}
          REQUESTED_BY: ${{ github.event.client_payload.requestedBy || github.actor }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          OPENROUTER_MODEL: ${{ secrets.OPENROUTER_MODEL }}
        run: |
          python scripts/split.py \
            --video-id "$VIDEO_ID" \
            --language "$LANGUAGE" \
            --max-duration "$MAX_DURATION" \
            --requested-by "$REQUESTED_BY"
      - name: Commit database update
        env:
          VIDEO_ID: ${{ github.event.client_payload.videoId }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add db/index.json data/
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update ${VIDEO_ID} split"
            git push
          fi
